POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/ff910a5f-64f2-4cc5-9f5d-30b39e8a871d
Content-Type: application/json

{
  "title": "Video 03",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

DELETE  http://localhost:3333/videos/ff910a5f-64f2-4cc5-9f5d-30b39e8a871d